version: '3'

services:
  web:
    image: matters-web:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: bash -c 'npm i && npm run dev'
    env_file: ../.env
    volumes:
      - ..:/var/app
      - node_modules:/var/app/node_modules
    ports:
      - '3000:3000'

volumes:
  node_modules:
