name: Deployment

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - '*'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MATTERS_SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12.16'

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: |
          npm run gen:clean \
          && npm run gen:type \
          && npm run lint \
          && npm run format:check

      # - name: Test
      #   run: npm install codecov -g && npm run test && codecov
      #   env:
      #     CODECOV_TOKEN: f109cbf6-b6c7-4a08-ad03-981bc4cd1fe8
      #     MATTERS_ENV: test
      #     API_URL: http://matters-server-develop.ap-southeast-1.elasticbeanstalk.com/graphql

      # - name: Test - BDD

      # === `develop` branch ===
      - name: Build (devlop)
        # if: github.ref == 'refs/heads/develop' || github.base_ref == 'develop'
        run: cp .env.dev .env && npm run build

      - name: Against SEO (develop)
        # if: github.ref == 'refs/heads/develop'
        run: |
          cp .ebextensions/http-basic-auth.config.dev .ebextensions/http-basic-auth.config

      # === `master` branch ===
      - name: Build (production)
        if: github.ref == 'refs/heads/master' || github.base_ref == 'master'
        run: cp .env.prod .env && npm run build

      - name: Setup AWS
        # if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Generate deployment package
        # if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
        run: zip -r deploy.zip . -x node_modules/\* .git/\*

      # === `develop` branch ===
      - name: Upload Assets (devlop)
        # if: github.ref == 'refs/heads/develop'
        run: |
          aws s3 sync .next s3://web-develop.matters.news/_next

      - name: Deploy to EB (develop)
        # if: github.ref == 'refs/heads/develop'
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: matters-stage
          environment_name: matters-client-web-develop
          version_label: matters-web-develop-${{ hashFiles('deploy.zip') }}
          version_description: ${{ github.SHA }}
          region: ap-southeast-1
          deployment_package: deploy.zip
          use_existing_version_if_available: true

      # === `master` branch ===
      - name: Upload Assets (production)
        if: github.ref == 'refs/heads/master'
        run: |
          aws s3 sync .next s3://matters.news/_next

      - name: Deploy to EB (production)
        if: github.ref == 'refs/heads/master'
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: matters-prod
          environment_name: matters-client-web-prod
          version_label: matters-web-prod-${{ hashFiles('deploy.zip') }}
          version_description: ${{ github.SHA }}
          region: ap-southeast-1
          deployment_package: deploy.zip
          use_existing_version_if_available: true

      - name: Slack Notification
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: matters-web
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
